### PR TITLE
Initial effort to move front-end libs to NPM

### PR DESCRIPTION
**Pull request by Teodor92**
**Changes:**
- moved all the front end libs from NuGet to npm
- using webpack to move packages from node_modules to ./Dependencies/
- removed all old libs from the Content and Script folders

**What is left to do:**
- move bundling and minifyring to webpack 
- use webpack module bundling for each page
- use Babel transpilation to support ES6
- refactor JS files
- move away from gulp and integrate everything in webpack and npm.

How to run webpack? Use the [npm build system](https://www.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/) in the web project root directory:
`npm run build`. This will run the linting and webpack processes.

Note - this should be **tested with real system data** to ensure no regression was introduced. I did a couple of local tests but my data sample is limited.

### CODE REVIEW

**Comment by KristianMariyanov** [comment]
Good Job 👍

**Comment by Teodor92** [comment]
68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3135333034352f32343930312f62396535363132302d346163342d313165322d393035612d3833353061643532613965342e6a706567

**Comment by jicata** [comment]
We will need some more time to figure out how to run through and thoroughly test the newly introduced changes. So hold tight for now please :)

**Comment by Teodor92** [comment]
If you need more information about the changes - post the questions here and I will answer. :)

**Comment by YanaSlavcheva** [comment]
@Teodor92 Please, fix conflicts so that @jicata can merge finally. Thank you!

**Comment by Teodor92** [comment]
Done.

**Comment by Teodor92** [comment]
Note: that code is already in the repo - this was a merge commit.

**Comment by KristianMariyanov** [comment]
Oooh. 😆

**Comment by rozay** [comment]
@Teodor92 I think someone will get the Hacktoberfest T-Shirt 😸 👍

**Comment by Teodor92** [comment]
@rozay 

a1kpqk2_700b

**Pull request merged**
