### PR TITLE
JQuery downgrade

### PR DESCRIPTION
**Pull request by Teodor92**
- Downgraded jQuery to version 2 as the KendoUI version in the OJS does not support 3. It is a good idea to update KendoUI
- Fixed ESLint errors
- Minor updates for other NPM packages

### CODE REVIEW

**Comment by Teodor92** [comment]
Maybe it is a good idea to remove the NPM packages form the source control.

**Comment by jicata** [comment]
Updating KendoUI would be great, however it's not something we can afford to consider at the moment. As a result we have to deal with whatever limitations the currently used version brings to the table.

**Comment by Teodor92** [comment]
Understood, then it is a good idea to downgrade JQuery as currently most of the KendoUI components are broken.

**Comment by jicata** [comment]
I've a question about removing the NPM packages from source control. Will that result in having to run `npm run build` at least once before starting the project?

**Pull request merged**
